plugins {
    id 'com.android.library'
}

android {
    compileSdk Build.compile_sdk_version

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    defaultConfig {
        minSdkVersion Build.min_sdk_version
        targetSdkVersion Build.target_sdk_version
    }
    buildTypes {
        release {
            minifyEnabled false
        }

        debug {
            minifyEnabled false
        }
    }
    namespace 'com.github.clans.fab'
}

dependencies {
    implementation Libs.support_appcompat_v7
    implementation Libs.support_design
}
